# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a57434b89b62a320543f7abd93616ce665ef84880d304fd9a576d9c61beaa1a01fb420cb5237caf4f7020fbea2c9c081658ca02b2ac282891937520f6f8da05

test:
  secret_key_base: 47dd689ace9b299b528eccff9108b444da5c4bb6ecc67c9b5c43a856e9e837f1618f64bc3c395da462c4d10a99c8172626f9e9a1d30121dd3e0d83a17ce2b426

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
